version: '2'
services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret_password
      - MYSQL_USER=gyazai_user
      - MYSQL_PASSWORD=gyazai_user_password
    ports:
      - "53306:3306"
  python:
    build: ./python
    volumes:
      - ./python/data:/gyazai/data
      - ./python/logs:/gyazai/logs
      - ./python/script:/gyazai/script
    tty: true
    links:
      - mysql
